services:
  nginx:
    image: nginx:1.31.0
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
    depends_on:
      cat:
        condition: service_healthy
      dog:
        condition: service_healthy
  cat:
    image: 127.0.0.1:5000/api:1.0
    environment:
      PET: ${CAT_SERVICE_PET}
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/healthz" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
  dog:
    image: 127.0.0.1:5000/api:1.0
    environment:
      PET: ${DOG_SERVICE_PET}
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/healthz" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - '${GRAFANA_PORT}:3000'
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
    depends_on:
      prometheus:
        condition: service_healthy
  prometheus:
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
    depends_on:
      nginx:
        condition: service_healthy
      node-exporter:
        condition: service_healthy
      cadvisor:
        condition: service_healthy
  node-exporter:
    image: prom/node-exporter:v1.8.1
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9100/" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 3s
  portainer:
    image: portainer/portainer-ce:2.41.1
    ports:
      - '${PORTAINER_PORT}:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  grafana_data:
  portainer_data: